artifacts:
    ARTIFACTS_DIR: 'artifacts'
    TRAINED_MODEL_DIR: 'model'
    BASE_MODEL_DIR: 'base_model'
    BASE_MODEL_NAME: 'base_model.h5'
    UPDATED_BASE_MODEL_NAME: 'updated_model.h5'
    CHECKPOINT_DIR: 'checkpoint'
    BASE_LOG_DIR: 'base_model_dir'
    TENSORBOARD_ROOT_LOG_DIR: 'tensorboard_log_dir'
    CALLBACKS_DIR: 'callbacks'
    DATA_DIR: 'data'

source_data_dirs:
    - ../data_source/cat
    - ../data_source/dog

local_data_dirs:
    -  data/cat
    -  data/dog
